// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAVzJZVBdK22nET9CrY2j9IILHJl8w2Y8',
    appId: '1:510980049965:web:5d34675620c18503ae3ca4',
    messagingSenderId: '510980049965',
    projectId: 'chatapp-e1837',
    authDomain: 'chatapp-e1837.firebaseapp.com',
    storageBucket: 'chatapp-e1837.appspot.com',
    measurementId: 'G-3506923N9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZGXeuJcSxqdfsLUTjDrWD3aBGNm-l2aY',
    appId: '1:510980049965:android:23f0be509f1ba98cae3ca4',
    messagingSenderId: '510980049965',
    projectId: 'chatapp-e1837',
    storageBucket: 'chatapp-e1837.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL8M85ockr3Va2DqM4PAI3csXNCYchcPA',
    appId: '1:510980049965:ios:2e6e4359643c961dae3ca4',
    messagingSenderId: '510980049965',
    projectId: 'chatapp-e1837',
    storageBucket: 'chatapp-e1837.appspot.com',
    iosBundleId: 'com.example.chatAppProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL8M85ockr3Va2DqM4PAI3csXNCYchcPA',
    appId: '1:510980049965:ios:2e6e4359643c961dae3ca4',
    messagingSenderId: '510980049965',
    projectId: 'chatapp-e1837',
    storageBucket: 'chatapp-e1837.appspot.com',
    iosBundleId: 'com.example.chatAppProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAVzJZVBdK22nET9CrY2j9IILHJl8w2Y8',
    appId: '1:510980049965:web:d67423df8348499fae3ca4',
    messagingSenderId: '510980049965',
    projectId: 'chatapp-e1837',
    authDomain: 'chatapp-e1837.firebaseapp.com',
    storageBucket: 'chatapp-e1837.appspot.com',
    measurementId: 'G-68LFSB0T9G',
  );
}
